### ISSUE TITLE
[Cloud Code] Local `skygear` package will overwrite the global one

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-SDK-JS#123]
Currently, when the deployed cloud code contains `package.json` and `skygear` is included, the cloud code will not be loaded.

**Comment by cheungpat** [comment]
Need info from @rickmak to know how to move forward about this.

**Comment by rickmak** [comment]
First. I think it is valid for end-user to include a `package.json` in his projects.


The problem should be we are using `npm install -g` in `skygeario/skygear-node` docker image. But we only do `npm install` (no -g) in cloud-app. So just add `-g` in the cloud-app should make things all load from the global.

The resulting behaviour will be:
1. we provide latest skygear-node by default
1. if he specific older skygear-node in package.json, we will install that version. Override the version we installed.

**Comment by cheungpat** [comment]
> So just add -g in the cloud-app should make things all load from the global.

that’s okay!

**Comment by cheungpat** [comment]
This will be fixed in the next cloud image update
