### ISSUE TITLE
Allow specifying Mime when uploading asset to Record

### ISSUE THREAD

**Issue by b123400** [SkygearIO/skygear-SDK-JS#148]
iOS SDK has this function https://github.com/SkygearIO/skygear-SDK-iOS/blob/eb6b19fd17a00c5c58cb296abd9156df5475ad79/Pod/Classes/SKYAsset.h#L38

**Comment by akiroz** [comment]
I think the MIME type should be automatic, since the JS `File` object has an MIME type.

**Comment by rickmak** [comment]
The current asset can specify the `contentType`
