### ISSUE TITLE
Make the example to support cloud deployment endpoint

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-JS#15]
Make the configuration of end point to be an text input.

**Comment by cheungpat** [comment]
I don’t understand the “without recompiling” part.

**Comment by rickmak** [comment]
Yes, I mistaken. We can change the endpoint now without go through webpack.

**Comment by rickmak** [comment]
@bensonby A live demo is now available at https://sdkjsexample.skygeario.com/static/example/index.html

Push to master will auto update the above link.
