### ISSUE TITLE
Cloud code includeme like python

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-JS#155]

**Comment by ben181231** [comment]
Skygear Plugin Initialization Convention
========================================

For Skygear Plugins, they should not be initialized when they are imported by
other modules. All Initialization should be wrapped into a function named
`includeme` as following:

```python
import skygear

def includeme(settings, *args, **kwargs):
    @skygear.op('some:lambda')
    def some_lambda_func():
        return {
            'success': True,
            'message': 'Some message being returned'
        }

    @skygear.after_save('some_record', async=True)
    def some_record_after_save(record, original_record, db):
        return {
            'success': True
        }

    # other lambda functions

```

The `includeme` function will be called in the following cases:

1. The module is declared on Skygear Plugin Runner, i.e. execute
   `py-skygear some_module`.

2. The module is configured in cloud code, i.e. user calls
   `skygear.config('some_module')` in his cloud code.

When the `includeme` function is called, all plugin settings are passed as
argument. Plugins can add their own settings parser:

```python
from skygear.settings import SettingsParser, add_parser

smtp_settings_parser = SettingsParser('SMTP')
smtp_settings_parser.add_setting('host', resolve=False, required=False)
smtp_settings_parser.add_setting('port', resolve=False, default=25, atype=int)
smtp_settings_parser.add_setting('login', resolve=False, default='')
smtp_settings_parser.add_setting('password', resolve=False, default='')

add_parser('smtp', smtp_settings_parser)

```

**Comment by cheungpat** [comment]
Seems I have yet to make a pull request for this issue.
