### ISSUE TITLE
Consider switching to use explicit react related config instead of implicit determine

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-JS#160]
In `container.js` and `store.js`, there is a `require('react-native');` clause. The cause create `Cannot find module` in some environment, like ionic. It will required extra configuration to set `react-native` to `undefined` when using webpack bundling.

- Skygear SDK Date/Version: 0.21.0
- JS runtime:
- Skygear Server Date/Version: 0.21.0
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

**Comment by david90** [comment]
@rickmak How to workaround at this moment?

**Comment by rickmak** [comment]
It depends on what bundler you are using. For webpack, you can mark react-native as external to make  the bundle works. If you are using generator, we do it for you: https://github.com/SkygearIO/generator-skygear/blob/master/generators/index.js#L114

**Comment by david90** [comment]
@rickmak  Using Ionic (ionic1), when require using browerify, it cannot find module.

**Comment by calvinchankf** [comment]
@rickmak it works on webpack1 but how to make it work on webpack2?

I tried the same as the skygear boilerplate
```
externals: {
    'react-native': undefined,
    'websocket': undefined
  }
```
but it shows WebpackOptionsValidationError when I compile the project
https://drive.google.com/file/d/0B4GsONVca8IOSDNfN01Yc04yWmc/view

Instead, I tried
```
externals: [ 'reactive', 'websocket' ]
```
It compiled successfully but my project doesn't recognize `react` instead
https://drive.google.com/file/d/0B4GsONVca8IOalJVZDFKLV81QWc/view?usp=sharing

Please help

**Comment by b123400** [comment]
I sent a PR https://github.com/SkygearIO/skygear-SDK-JS/pull/206 that works around the issue. It's preventing webpack from bundling react-native, which means it is not following the suggestion solution in this issue. Because:

- Less config is better
- Config is not always available
  - When an angular project is created via the official `angular-cli`, it does not expose any option to config the packaging process, [intentionally](https://github.com/angular/angular-cli/issues/1656#issuecomment-239366723).

Actually after this PR, angular / ionic / webpack does not need any extra config to use skygear, which means a normal `require('skygear')` is already good enough. Maybe we don't need https://github.com/SkygearIO/guides/issues/58 as well.

**Comment by chpapa** [comment]
> Maybe we don't need SkygearIO/guides#58 as well.

We could then focus the issue on a react.js guide / boilerplate...?

**Comment by b123400** [comment]
Sorry, the PR #206 failed, it doesn't work. We need config.

I am not sure where should we put the config. I cannot think of a place to accept options except for asking user to update their webpack config, but that would be just like the current situation.
@rickmak 

I can write guides to tell user to make `react-native` optional (externals), but that doesn't always work. User might [not have access](https://github.com/angular/angular-cli/issues/1656#issuecomment-239366723) to their webpack config.

Or should we make 2 different packages?

- `skygear`
- `skygear-react-native`, exports everything from `skygear`, and override things like store
  - Refactor might be needed to make things overridable

**Comment by rickmak** [comment]
Let have two packages.

`skyegar` and `skygear-react-native`

- Usage at normal js webpack: `const skygear = require('skygear');`
- Usage at react-native: `const skygear = require('skygear-react-native');`

What `skygear-react-native` do is import `skygear` modify the store, re-export the modified skygear container.

`skygear-react-native` should be a simple package have actual store implementation. And a thin container re-export code.

The refactor needed - Make store dependency injectable to container constructor.

* Don't go for preprocessors. If they can use gulp preprocessors, they can modify the webpack config.

**Comment by rickmak** [comment]
Please take a look at https://github.com/lerna/lerna. We do not want to maintain multiple repositories for this purpose.

**Comment by b123400** [comment]
Looked at how lerna manages packages and I don't think we should use it. It puts packages into the `packages` folder, and there is no "root" package.

E.g. In react, the root level is a package called [`react-build`](https://github.com/facebook/react/blob/master/package.json), the real `react` is at `packages/react`. If I have to use lerna, I will need to move all files to a subdirectory, and therefore update all build tools and might break something.

Moreover, I realise we already have an existing pattern for solving differences between platforms, which is the `lib/cloud` folder. By asking using to `require('skygear/cloud')` we can do whatever injection we like, so I implemented the react-native part via `require('skygear/react-native')`.

**Comment by rickmak** [comment]
Thx @b123400 for PR. I think it is good to merge. To make this accessible to users, we will need the following too:

- [ ] A doc/tutorial on how to incoporate it into react-native
- [ ] An example app in https://github.com/skygear-demo
