### ISSUE TITLE
[Bug] Uncaught TypeError: rb is not a function

### ISSUE THREAD

**Issue by IniZio** [SkygearIO/skygear-SDK-JS#190]
(Describe the issue here)

- Skygear SDK Date/Version: 0.22.2
- JS runtime: Typescript 2.2.2
- Skygear Server Date/Version:
- [ ] Is this a regression?
- [X] Attached logs, screenshots

#### Actual Results
![image](https://cloud.githubusercontent.com/assets/3119725/25071370/9f6cb33e-22e7-11e7-84e2-c506b55e81a0.png)

#### Steps to reproduce
1. `require('skygear')` already triggers the error

#### Remarks
- Uses electron

**Comment by cheungpat** [comment]
Hi @IniZio. Thanks for filing an issue. I am not sure how to reproduce the error you are having. Could you tell me which guide you followed and is there a demo project to illustrate the problem?

**Comment by IniZio** [comment]
Sorry, turned out that it is due to my build tool not opening up nodejs libraries to the bundle, leading to the app not able to use `rb = require('crypto').randomBytes`, and thereby causing the error. Issue can be closed

**Comment by cheungpat** [comment]
Oh I see. That’s okay. Thanks for letting me know. : )
