### ISSUE TITLE
Add descriptions for API reference

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/skygear-SDK-JS#193]
Reference: [SkygearIO/features#54](https://github.com/SkygearIO/features/issues/54)
Since JS SDK have **no auto-completion** like iOS / Android, the option fields and return types on documentation are relatively important for developers to do implementations. This issue would like to complete some of the descriptions of the API references that are frequently used by other developers.

Aiming to at least fill those **input param, option fields & return types** for those frequently used APIs. It would be great if we can add example there. 

### Waiting for completion:
- [ACL](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/acl.js~ACL.html)
- [Asset](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/asset.js~Asset.html)
- [Cache](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/cache.js~Cache.html)
- [Datebase](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/database.js~Database.html)
- [SkygearError](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/error.js~SkygearError.html)
- [Query](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/query.js~Query.html)
- [QueryResult](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/query_result.js~QueryResult.html)
- [Record](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/record.js~Record.html)
- [User](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/user.js~User.html)
- [EventHandle](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/util.js~EventHandle.html)
- [op](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-op)

### Double check if these have been completed: 
- [BaseAuthProvider](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/cloud/index.js~BaseAuthProvider.html)
- [staticAssetHandler](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-staticAssetHandler)
- [event](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-event)
- [every](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-every)
- [hook](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-hook)

**Comment by tensiuyan** [comment]
Ref: https://github.com/SkygearIO/skygear-SDK-JS/blob/master/lib/cloud/index.js#L105

**Comment by chpapa** [comment]
op is missing, so I moved it from "Double check" to "Waiting for completion"

**Comment by chpapa** [comment]
This issue is too large which practically no one would dare to take it on... I guess I will close it for now.
