### ISSUE TITLE
Allow configuration of pg pool size

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-JS#201]
`node-postgres` allow configuration of min, max and idleTimeoutMillis of pool size. But we are not exposing it for configuration.

- Skygear SDK Date/Version: 0.23.0, 21 Apr 2017
- JS runtime: skygear-node

**Comment by ckanthony** [comment]
Hello!  Where do you want to config this?  Via the ENV variable?

```
PG_MAX=10
PG_MIN=4
PG_IDLE_TIMEOUT_MILLIS=1000
```

What do you want for default value or leave `pg-pool` to set the default?

**Comment by rickmak** [comment]
Yes, via ENVVAR. I would expect following:

```
PG_POOL_MAX=10
PG_POOL_MIN=4
PG_POOL_IDLE_TIMEOUT_MILLIS=30000
```

Above default should make sense for common cases.

The setting should be stored here: https://github.com/SkygearIO/skygear-SDK-JS/blob/master/lib/cloud/settings.js
