### ISSUE TITLE
[OAuth] API for integrating OAuth

### ISSUE THREAD

**Issue by b123400** [SkygearIO/skygear-SDK-JS#204]
connect https://github.com/SkygearIO/features/issues/5

- [ ] `loginWithOAuthProvider(providerID, options, [accessToken])`
  - Create or login a new skygear user, associated with the provider
  - `providerID` - A string that identify the login provider
  - `options`
    - uxMode - Either `popup`(default), or `redirect`
    - clientID
    - scope
    - redirectUrl - when uxMode is `redirect`, skygear will redirect the user to this url after auth. If it is null, back to the current URL
  - `accessToken` - Optional. Pass in access token if client already has it, skygear will try to login directly instead of going through the OAuth flow.
  - Calls `oauth:auth_url`, or `oauth:handle_access_token`
  - This function returns a skygear user, and an access token of the service.
- [ ] `associateAccountWithProvider(providerID, options)`
  - Add a new auth provider to the user by going through the auth flow
  - This API requires user to be logged in already, return error otherwise
  - `providerID` - A string that identify the login provider
  - `options`
    - uxMode - Either `popup`(default), or `redirect`
    - clientID
    - scope
    - redirectUrl - when uxMode is `redirect`, skygear will redirect the user to this url after auth. If it is null, back to the current URL
  - This function returns a skygear user, and an access token of the new service.

- [ ] `getOAuthTokens()`
  - Calls skygear-server `user:oauth_tokens`
  - Return a promise of tokens

        getOAuthTokens().then(function(tokens){
          //tokens['com.facebook'] is FB's access token
        });

------

```
skygear.loginWithOAuthProvider('com.example', {
  clientID: 'xxxxxxx',
  uxMode: 'popup',
  scope: 'email'
}).then(skygearUser => {
  // At this point, the user is logged in
  skygear.getOAuthTokens().then(function(tokens){
    //tokens['com.example'].accessToken is the access_token
  });
})
```

**Comment by rickmak** [comment]
I think `getOAuthTokens(providerID)` is better and more symmetry to the rest of the API? Missing `providerID` will return all OAuthToken.
