### ISSUE TITLE
Pub/Sub can only publish JS truthy values

### ISSUE THREAD

**Issue by akiroz** [SkygearIO/skygear-SDK-JS#228]
Pub/Sub can only publish JS truthy values

- Skygear SDK Date/Version: 0.23.0

#### Expected Results
EITHER pubsub accept any serializable JS value
OR pubsub message requires a single Object/Array as per the JSON spec

#### Actual Results
`skygear.pubsub.publish` will throw an exception if the message body is JS falsey.
i.e. `42`, `"hello"`, `[]` and `{}` works but `0`, `""`, and `null` does not.

**Comment by Steven-Chan** [comment]
@rickmak I suggest restricting the pubsub message to JSON object/dictionary only to make it consistent across all SDK.
