### ISSUE TITLE
Host class doc on the project’s domain

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-SDK-JS#243]
Since https://github.com/SkygearIO/skygear-SDK-JS/commit/3a440180e15b94054a46e24b8a7b5a3e1d3b719f, the JS SDK requires esdoc plugin to generate the full esdoc, but plugin is not supported by esdoc hosting service https://github.com/esdoc/esdoc-hosting/issues/16.

We need to host our own esdoc just like the Android SDK.

**Comment by rickmak** [comment]
Resolved: https://docs.skygear.io/js/reference/latest/
