### ISSUE TITLE
Unable upload Asset record from Node

### ISSUE THREAD

**Issue by yipsang** [SkygearIO/skygear-SDK-JS#251]
(Describe the issue here)

- Skygear SDK Date/Version: 1.0
- JS runtime: node v8.1.3
- Skygear Server Date/Version:
- [x] Is this a regression?
- [ ] Attached logs, screenshots

```
var skygear = require('skygear');

var createDummySCN = function() {
	const SCN = skygear.Record.extend('scn');

	const scnAsset = new skygear.Asset({
		name: 'dummy.scn',
		base64: '4pyTIMOgIGxhIG1vZGU=',
		contentType: 'application/octet-stream'
	});
		
	const scn = new SCN({
		name: 'dummy',
		attachment: scnAsset 
	});

	return scn;
}

console.log("Creating dummy scn and texture record ...");

skygear.config({
	'endPoint': 'xxx', // trailing slash is required
	'apiKey': 'xxx',
}).then(() => {
	return skygear.auth.loginWithUsername('admin', 'secret');
}).then(() => {
	console.log("Saving scn record to db ...");

	const scn = createDummySCN();
	return skygear.publicDB.save(scn);
}).then((record) => {
	console.log(record);
	console.log("Record attachment: " +record.attachment.url);
}).catch((err) => {
	console.error('Error in creating scn: ' + err.message);
})
```

**Comment by rickmak** [comment]
The asset can be uploaded, but the asset model is created. 

The https://github.com/SkygearIO/skygear-SDK-JS/blob/7c516a0/packages/skygear-core/lib/database.js#L117 is expecting a file object. The `asset.file` is a `Blob` file which is not confront with the interface that superagent is expecting. Thus will rasie exception on `on` and `pause` method not defined.

**Comment by chpapa** [comment]
@rickmak I don't understand what do you meant in your last comment. What do you meant by "The asset can be uploaded, but the asset model is created."?

**Comment by chpapa** [comment]
And shall we close this issue? Please advices.

**Comment by rickmak** [comment]
> The asset can be uploaded, but the asset model is created.

Should be -> The asset can't be uploaded, the asset model is created.

i.e. as asset model in Postgres is created but pointing to a file does not exist.

It need to be address.

Side note: browser run time work fine.

**Comment by carmenlau** [comment]
Should be fixed in https://github.com/SkygearIO/skygear-SDK-JS/pull/412
