### ISSUE TITLE
[BUG] `this.store.clearPurgeableItems` is not a function

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-SDK-JS#303]
App crashes when calling `skygear.clearCache()` in react-native

React native storage driver is exported in https://github.com/SkygearIO/skygear-SDK-JS/blob/master/packages/skygear-core/lib/react-native/store.js#L91 and container's store is set to `ReactNativeAsyncStorageDriver` in https://github.com/SkygearIO/skygear-SDK-JS/blob/master/packages/skygear-core/lib/react-native/index.js#L16 . Which is very **WRONG**.

- Skygear SDK Date/Version: 0.24.1 (I checked the implementation in current master and it is still wrong)
- JS runtime: react-native
- Skygear Server Date/Version: 0.24.1
- [x] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
We can clear cache successfully

#### Actual Results
App crashed

#### Steps to reproduce
Call `skygear.clearCache()`

**Comment by Steven-Chan** [comment]
Thanks @cychiuae.

Please see https://github.com/SkygearIO/skygear-SDK-JS/blob/v0.21.0/lib/store.js#L478 for the correct implementation.

`react-native/store.js` is exporting driver, but `setStore` in `react/store.js` expects store object.
