### ISSUE TITLE
skygeario/skygear-node:v1.1.0 on hub.docker.com is not working

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-JS#314]
skygeario/skygear-node                           latest                9d3cbc2127f4        7 weeks ago         657MB

- Skygear SDK Date/Version: 1.1.0
- JS runtime:
- Skygear Server Date/Version: 29 Sep, 2017
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results

```
docker run -it --rm -v "$PWD":/usr/src/app skygeario/skygear-node:canary
Listening 0.0.0.0 on port 9000...
```

#### Actual Results

```
docker run -it --rm -v "$PWD":/usr/src/app skygeario/skygear-node:latest
[FATAL tini (6)] exec skygear-node failed: No such file or directory
```

#### Steps to reproduce

1. docker pull skygeario/skygear-node:latest
2. docker run -it --rm -v "$PWD":/usr/src/app skygeario/skygear-node:latest

**Comment by cheungpat** [comment]
um... the `latest` tag refers to the latest released version which is currently 1.1.0 and 1.1.0 is released two months ago. That’s why the `latest` tag is also 2 months old.

The `canary` tag is the cutting edge version, and this tag is updated each time we update `master` branch.

Confusing?

**Comment by rickmak** [comment]
I am not saying the build pipeline not properly setup.

The latest tag is 2 months old which expected to me. I want to say the docker image is not properly built, hence the image is not ready to use. But I can run `skygear-node` with v1.1.0 if I install it locally.

For reference, v1.1.0 image is not work too

```
docker run -it --rm -v "$PWD":/usr/src/app skygeario/skygear-node:v1.1.0
[FATAL tini (7)] exec skygear-node failed: No such file or directory
```

**Comment by cheungpat** [comment]
ooooh? you mean the image is broken? let me take a look

**Comment by cheungpat** [comment]
fixed by uploading a new image, it should work now, apologise for not catching this earlier @rickmak

**Comment by cheungpat** [comment]
not reproducible from my side and the version on travis is having problem because of missing dependencies 😕

suspect that the problem is due to the skygear package version being `1.1.0-beta.1` which the dockerfile cannot find when building the image.

**Comment by rickmak** [comment]
Great, thanks.
