### ISSUE TITLE
Lookup user by username

### ISSUE THREAD

**Issue by TakLee96** [SkygearIO/skygear-SDK-JS#32]
We have `skygear.getUsersByEmail([ ... ])`, then why not `skygear.getUsersByUsername([ ... ])`?

**Comment by cheungpat** [comment]
@rickmak How to query user record by email in JS SDK?

**Comment by cheungpat** [comment]
The `getUsersByEmail` should be changed so that it return `Record` instead of `User`. Alternatively we can create a `discoverUsersByEmail` that will return `Record`.
