### ISSUE TITLE
Cannot require skygear in node

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-SDK-JS#35]
`require('skygear');` will result error.

- Skygear Server Date/Version: v0.13
- Application Platform:
- [x] Is this a regression?

#### Expected Results
It works with in process memory storage

#### Actual Results

Error: Cannot find module 'localStorage'`

#### Steps to reproduce

1. npm install skygear
1. node
1. require('skygear');

**Comment by TakLee96** [comment]
I think it's just because npm module `localStorage` is in `devDependencies` but not `dependencies` in `package.json`.

**Comment by rickmak** [comment]
Resolved at 7bc2537
