### ISSUE TITLE
Login with custom token api

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-SDK-JS#359]

**Comment by KhaledAld** [comment]
@carmenlau  
can logged in users from CloudJS function ??

**Comment by carmenlau** [comment]
@KhaledAld Normally we will not login user in cloud functions, instead we can send action to server on behalf of the user in cloud function. But we need to make sure the cloud function is protected correctly (e.g. user_required). What is your use case?

**Comment by carmenlau** [comment]
@KhaledAld In your case, you should not need to do the login in cloud function? Instead you can use the client SDK to login user with the custom token.

The possible flow:

1. Client app call your server with login credential (maybe username password), your server check and return the custom token (generated in your server) to client.
1. Use the client SDK to login user with the custom token

For your reference:
https://docs.skygear.io/guides/auth/custom-token/ios/

**Comment by KhaledAld** [comment]
I do this flow, I will explain in sample example 
I have three users in my custom server A,B,C
I create JWT for these users 
now A and B login with a custom token 
A, B can make a chat between us 
but if user A wants to chat with user C (C is not logged in  to skygear)

I want to add all users in my server to skygear server (this step just for one time ) to make all user available when a user wants to make a chat with any user in the system

thanks.
