### ISSUE TITLE
[React native] Compatibility issue of localforage

### ISSUE THREAD

**Issue by TakLee96** [SkygearIO/skygear-SDK-JS#39]
- f070946 or also know as tag v0.13.0 (current npm stable release) is missing localStorage
- 7bc2537 solves the above issue but is not published to npm yet
- 5c18812 upgrades localforage (webpack no longer brings any error about localforage) but makes react-native projects crash

Step to reproduce the error:
- `npm install -g react-native-cli`
- `react-native init BuggyProject` (takes 5 minutes)
- Edit `package.json` to include `"skygear": "github:bensonby/skygear-SDK-JS-1#0.14-test-custom-build"` inside `dependencies`
- `npm install`
- Edit `index.ios.js` to have `import skygear from 'skygear'` in the first line of code
- `react-native run-ios`

```
transformed 681/682 (100%)[node-haste] Encountered an error while persisting cache:
> ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/localforage/.babelrc" at 0, attempted to resolve relative to "/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/localforage"
>     at /Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
>     at Array.map (native)
>     at Function.normalisePlugins (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
>     at OptionManager.mergeOptions (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
>     at OptionManager.init (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
>     at File.initOptions (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/file/index.js:223:65)
>     at new File (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/file/index.js:140:24)
>     at Pipeline.transform (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
>     at transform (/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/react-native/packager/transformer.js:108:26)
> TransformError: /Users/lijiahang/Developer/oursky/BuggyProject/node_modules/localforage/dist/localforage.js: Unknown plugin "add-module-exports" specified in "/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/localforage/.babelrc" at 0, attempted to resolve relative to "/Users/lijiahang/Developer/oursky/BuggyProject/node_modules/localforage"
```

[Localforage](https://github.com/localForage/localForage#user-content-browserify-and-webpack) github repo has talked about installing additional dependencies for build systems, so I proceeded with installing the following (please also take a look at their `.babelrc` file):
- `npm install --save-dev babel-plugin-system-import-transformer`
- `npm install --save-dev babel-plugin-add-module-exports`
- `npm install --save-dev babel-preset-es2015`
- `npm install --save-dev babel-preset-es2015-loose`
- `react-native run-ios`

![Error](https://s31.postimg.org/5kzx3a7tn/2016_07_26_4_39_21.png)

**Comment by bensonby** [comment]
When finding ways to override the localforage in react-native environment:
https://github.com/facebook/react-native/issues/6253

**Comment by bensonby** [comment]
As @TakLee96 has tried, this can be fixed my removing the file `node_modules/localforage/.babelrc`. Possibly related issues:

- On react-native: https://github.com/facebook/react-native/issues/7850
- On localforage: https://github.com/localForage/localForage/issues/496

**Comment by rickmak** [comment]
Let try to update to babel 6 to see will it resolve.

**Comment by cheungpat** [comment]
> Let try to update to babel 6 to see will it resolve.

now or later?

**Comment by cheungpat** [comment]
> now or later?

consensus is later

**Comment by rickmak** [comment]
Upgraded to use babel6, and trigger react-native issue: https://github.com/facebook/react-native/issues/5747

Since the only variable is upgrade of babel and localforage. I suggest to drop localforage deps, to see if it relate.
