### ISSUE TITLE
Should not accept Null as api endpoint and give a confusing valid URL for default endpoint

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-JS#395]
Currently it mislead users by giving "http://myapp.skygeario.com" as default endpoint, when skygear sdk was configured with null as endpoint.

There are two problems:
1. We should throw error with invalid endpoint.
2. We should not use a valid URL as the default endpoint (in fact there are no default endpoint), it confuse users as the error message will be invalid api key instead of endpoint error

Please fix it if other SDK have similar problems

**Comment by carmenlau** [comment]
We will remove default endpoint for all SDK. When user makes request without config correct endpoint, will show error in console
