### ISSUE TITLE
JS cloud SDK stringify removed default attributes

### ISSUE THREAD

**Issue by david90** [SkygearIO/skygear-SDK-JS#397]
(Describe the issue here)

- Skygear SDK Date/Version: v1.3.3 
- JS runtime:
- Skygear Server Date/Version:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

Sample code to reproduce the problem:

```javascript
skygearCloud.handler('/try/', function (req) {
  return new Promise((resolve, reject) => {
    let container = getContainer('super');
    const Backlog = skygear.Record.extend('backlog');
    const query = new skygear.Query(Backlog);

    container.publicDB.query(query).then((result) => {
      console.log(result); // THE LOG SHOWS ALL ATTRIBUTES
      resolve(result); // THIS DOESN'T WORK
      // resolve(result.map(e => Object.assign({}, e))); // THIS WORKS
    }, (error) => {
      console.error(error);
      resolve("failed");
    });
  });
}, {
  method: ['GET']
});
```

#### Expected Results

should included default fields, createdAt, createdBy etc.

#### Actual Results

Didn't include default fields, createdAt, createdBy etc.

#### Steps to reproduce

1. Add the cloud function above 
2. try it on /try/ on the endpoint
3. the returned result didn't include default fields, createdAt, createdBy etc.

**Comment by carmenlau** [comment]
This issue is invalid now as we will support lambda with skygear data type in v1.6 which include record support. And now when user returns a record, all private columns are preserved.
