### ISSUE TITLE
Consistent error handling

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-SDK-JS#431]
https://github.com/SkygearIO/features/tree/master/features/190-consistent-error

**Comment by cheungpat** [comment]
@carmenlau @Steven-Chan If there is no problem, I am going to use Stage-2 decorator proposal to wrap all promise-returning functions (e.g. `signup`). The decorator will catch thrown Error and return a rejected promise instead.

Will look something like this:

```
@promisify
signup(authData, password, data = {}) {
  // implementation
}
```

Alternative: add the following in constructor:

```
this.signup = promisify(this.signup, this)
```

This is transparent to the user.

**Comment by cheungpat** [comment]
End up going to replace all promise returning function with async/await.
