### ISSUE TITLE
The bundle does not run on IE9

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-SDK-JS#435]
(Describe the issue here)

- Skygear SDK Date/Version: >=1.4.0
- JS runtime: IE9
- Skygear Server Date/Version: >=1.4.0
- [x] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
No error

#### Actual Results
Failed with `TypeError: Object expected`

#### Steps to reproduce

```html
<html>
<head>
<script src="https://code.skygear.io/js/polyfill/latest/polyfill.min.js"></script>
<script src="https://code.skygear.io/js/skygear/latest/skygear.min.js"></script>
<script>
  skygear.config({
    'endPoint': 'https://<your-app-name>.skygeario.com/', // trailing slash is required
    'apiKey': '<your-api-key>',
  }).then(function() {
    console.log('skygear container is now ready for making API calls.');
  }, function(error) {
    console.error(error);
  });
</script>
</head>
</html>
```
Save the above html as `index.html` and open it with IE9.

**Comment by carmenlau** [comment]
The error is due to lack of websocket support in IE9
