### ISSUE TITLE
Query > Pagination: The preference `overallCount` was not effective

### ISSUE THREAD

**Issue by cpryanpang** [SkygearIO/skygear-SDK-JS#46]
According to the docs https://docs.skygear.io/js/guide/query#pagination-ordering, under the sub-section **Counting the records**,
> To get the number of records matching a query, set the overallCount of the Query to true.

However, by real experiment, there was nothing at the second arguments of the success callback, e.g.:

```
query.overallCount = true;
skygear.publicDB.query(query).then(function(records, overallCount) {
	console.log('overallCount: ', overallCount);
});
```

it yields:
> overallCount: _undefined_

**Comment by ben181231** [comment]
I think the example in the documentation does not match our implementation. The expect usage would be:
```
query.overallCount = true;
skygear.publicDB.query(query).then((notes) => {
  console.log('%d records matching query.', notes.overallCount);
}, (error) => {
  console.error(error);
});
```

**Comment by cpryanpang** [comment]
Great. We can get the `overallCount` correctly.

Would you keep current implementation and modify the docs?

**Comment by ben181231** [comment]
@cpryanpang I would update the documentation.
