### ISSUE TITLE
Fail to bundle in react native

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-SDK-JS#462]
Cannot bundle my js code since introduction of `xml2js` in skygear-core . 

- Skygear SDK Date/Version: 1.6.3
- JS runtime: react-native
- Skygear Server Date/Version: N/A
- [x] Is this a regression?
- [x] Attached logs, screenshots

![simulator screen shot - iphone 8 - 2018-09-16 at 03 12 35](https://user-images.githubusercontent.com/10144357/45589780-9274e980-b95e-11e8-9a86-d7d6522562f8.png)

#### Expected Results
Can bundle with skygear sdk

#### Actual Results
Fail to bundle

#### Steps to reproduce

1. `react-native init HelloWorld`
2. `yarn add skygear`
3. import skygear in index.js to ensure skygear will be bundled

**Comment by Steven-Chan** [comment]
@cychiuae have you tried this? https://github.com/Leonidas-from-XIV/node-xml2js/issues/363#issuecomment-318935604

**Comment by Steven-Chan** [comment]
I just found a xml2js fork for react-native https://github.com/connected-io/react-native-xml2js.

**Comment by Steven-Chan** [comment]
@cychiuae could you help me verify if https://github.com/jindw/xmldom works on react-native? It says it works on node and browser.

**Comment by louischan-oursky** [comment]
@Steven-Chan FYI https://www.npmjs.com/package/fast-xml-parser
