### ISSUE TITLE
Test JS SDK for next (1)

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-SDK-JS#478]
Test /auth/signup handler 
https://oursky.quip.com/D7QOAajp94bL

**Comment by kaojohnny** [comment]
## notes

1. Submit a fix during the test: https://github.com/SkygearIO/skygear-server/pull/863.
2. `loginWithProvider` seems a skygear v0 API, do we have to support it in next?

**Comment by Steven-Chan** [comment]
@kaojohnny We no longer support `loginWithProvider` in next.

**Comment by kaojohnny** [comment]
@tensiuyan Do you think it is okay to close this issue? I think we should have another issue after skygear next revamp.
