### ISSUE TITLE
Unable to import defaultContainer in v2.0.0-alpha.15 using JS SDK

### ISSUE THREAD

**Issue by ChloeLo27** [SkygearIO/skygear-SDK-JS#543]
Trying to import defaultContainer from JS SDK results in a compiler error in yarn.

- Skygear SDK Date/Version: `v2.0.0-alpha.15`
- JS runtime: `yarn v1.15.2`
- Skygear Server Date/Version: `bea1cd1`
- [ ] Is this a regression?
- [x] Attached logs, screenshots

#### Expected Results
No error upon import of defaultContainer from `@skygear/web`

#### Actual Results
The following error message is found as react-scripts try to compile the react-app:
```
portal_1           | Module '"../../node_modules/@skygear/web"' has no exported member 'defaultContainer'. Did you mean 'WebAuthContainer'?  TS2724
portal_1           | 
portal_1           |     1 | import {
portal_1           |   > 2 |   defaultContainer,
portal_1           |       |   ^
portal_1           |     3 |   Container,
portal_1           |     4 |   AuthContainer,
portal_1           |     5 |   SkygearError,
```

#### Steps to reproduce

1. Include `"@skygear/web": "2.0.0-alpha.15",` under `dependencies` in `package.json` of a react app created by `create-react-app` command
2. Try to import `defaultContainer` from `@skygear/web` in one of the .tsx file
3. Compile with yarn

**Comment by louischan-oursky** [comment]
Was line 2 written by you?

**Comment by louischan-oursky** [comment]
Anyway I guess what you want to do is

```typescript
import skygear, { Container, AuthContainer } from "@skygear/web";
// skygear is the default container you are looking for.
```

**Comment by ChloeLo27** [comment]
> Was line 2 written by you?

I take the code in spaeglass as a reference.  I will change to simply `skygear` in this case.  Thanks!
