### ISSUE TITLE
[Bug] React native auth ui treats user cancel as unable to open url error

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-SDK-JS#573]
When press cancel in in browser of auth ui, sdk return error saying `Unable to open URL: (null)` and hence we cannot know if it is really an exception or user cancel/dismiss the browser

**Comment by louischan-oursky** [comment]
It may be possible to distinguish on iOS if ASWebAuthenticationSession or SFAuthenticationSession is used. But for other cases, it is unclear how to distinguish cancel from exception.

**Comment by carmenlau** [comment]
@louischan-oursky Besides detect the case, I think we need to decide how to return the error to user too. Currently we have `SkygearError` but now all of them are error return from server, see `SkygearErrorNames`. Return user cancelled error is a new case for us. Maybe we can choose either one of them?
1. Update `SkygearError` with new name, so `SkygearError` is not only representing server api return error
1. Return a generic JS error with special message + a util function for user to detect if the error is user cancel.
1. New error class

**Comment by louischan-oursky** [comment]
I prefer Option 3. Maybe name the new error class SDKError.

For the original problem, the error handling should look like

1. Check if it is `instanceof SkygearError`. If yes, it is an error generated by the server.
2. Check if it is `instanceof SDKError`. If yes, it is an error generated by the SDK.

```typescript
class SDKError extends Error {
  reason: string;
}
```

However, as noted in my previous comment, in this particular case, the promise may never resolve.

**Comment by carmenlau** [comment]
> in this particular case, the promise may never resolve

Yes, seems we can only detect when iOS > 10 and no way to detect in android, right? 
Or we should not reject the promise if it is user cancel case, so for all reject is real error. And when user use the `authorize` function, they should assume the `authorize` may never resolve , that would be user cancel case.

**Comment by louischan-oursky** [comment]
The promise must reject if the user cancels the operation. A resolved promise means cancel is too surprising. Basically the developer needs to be prepared for the following cases.

1. The promise never settle.
2. The promise rejects with SDKError (cancel).
3. The promise rejects with SkygearError.
4. The promise rejects with Error. This is usually a programming error that the developer has to deal with during development and this error should not leak to production.

**Comment by carmenlau** [comment]
Not calling resolve,🙈 what I meant is merging your case 1 and 2, since we cannot guarantee we can detect the cancel.

**Comment by louischan-oursky** [comment]
Oh, you mean we intentionally do not reject promise when we CAN detect cancel case. So all cancel case is a promise that never settle.

**Comment by carmenlau** [comment]
Yes, seems simpler to explain the behavior?  `authorize` will resolve when authorization success, reject when there is problem, will never settle if user cancel or leave the app.

**Comment by carmenlau** [comment]
@cychiuae We updated the `authorize` function behavior to 

- promise will be resolved when authorization success
- promise will be rejected if there is problem
- promise will never settle if user cancel or leave the app

And you can update the sdk `@skygear/react-native` to `v2.3.1` for the change.

**Comment by cychiuae** [comment]
@carmenlau 

It is okay to not settle the promise if user leaves the app because no much things we can do in this case. However, i believe we need to get notified when user cancels the flow, i.e. closing skygear auth ui.
