### ISSUE TITLE
How to detect cancel in authorization flow

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-SDK-JS#575]
With https://github.com/SkygearIO/skygear-SDK-JS/pull/574 if the user cancels the promise never settle. In some cases the developer may want to detect the cancel case.

Here is an idea to detect the cancel case. Pseudo code only!

```typescript
import { AppState } from "react-native";
import EventEmitter from "react-native/Libraries/vendor/emitter/EventEmitter";

class CancelWatcher extends EventEmitter {
  constructor(opts) {
    super();
    this.opts = opts;
  }
  watch() {
    if (this.watching) { return; }
    AppState.addEventListener("change", this.onAppStateChange);
  }
  onAppStateChange = (nextAppState) => {
    if (nextAppState === "active") {
      this.timeoutToken = setTimeout(this.onTimeout, this.opts.delayMillis);
    }
  };
  dispose() {
    if (this.timeoutToken) {
      clearTimeout(this.timeoutToken);
      this.timeoutToken = null;
    }
    if (this.watching) {
      AppState.removeEventListener("change", this.onAppStateChange);
      this.watching = false;
    }
  }
  onTimeout = () => {
    this.dispose();
    this.emit("cancel");
  };
}

async function foobar() {
  const cancelWatcher = new CancelWatcher({ delayMillis: 1000});
  cancelWatcher.addEventListener("cancel", function() {
    // Do something on cancel...
  });
  try {
    cancelWatcher.watch();
    await skygear.auth.authorize();
  } finally {
    cancelWatcher.dispose();
  }
}
```

**Comment by cychiuae** [comment]
This won't work in iOS because the webview is presented by root view controller and it will always trigger on cancel because app state will be changed from inactive to active when user presses the alert say "Do you want to open xxxx..."

**Comment by carmenlau** [comment]
@louischan-oursky Maybe we should re-consider detect it in the sdk to have a cancelled error?

For ios, I think maybe we can give up the old ios version, and we can detect cancel for ios version >= 11. We can keep the logic there for the old ios version, but the promise will never resolve if user leave the authorization flow.
refs: https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/worldwide

For android, maybe we can try detect it? We can add a delayed checking in `onHostResume`, if user go back to the app and the promise is not resolved. User should cancel the flow and SDK can reject the promise with cancelled error and remove the promise reference?

Thought?

**Comment by louischan-oursky** [comment]
If I were the developer, I would suggest removing cancel-specific app logic.

The behavior is inconsistent across iOS version. If the application is targeting both "old" iOS and "new" iOS, it complicates the handling.

Your suggested approach for Android should work for iOS as well. But I tend not to add such detection in the SDK. Instead it should be a Oursky library.

The idea is to detect when the app becomes active, whether Condition A happens with some delay. In this particular case, Condition A is authenticated status.

**Comment by carmenlau** [comment]
ummm, not sure what you mean for 

> I would suggest removing cancel-specific app logic

?

You mean not to detect?

Not sure why developer will want to know if the authorization flow is cancelled, for analytics? @cychiuae

**Comment by louischan-oursky** [comment]
I mean I would convince the stakeholder not to add cancel-specific logic if the piece of logic is critical to the app. Cancel detection is not 100% robust.

If flaws in cancel detection is acceptable, such as the stakeholder just want to have tracking on how many users cancel the flow, then we can go for inventing a library for cancel detection.

**Comment by carmenlau** [comment]
ok, I got what you mean. Then maybe we need to have input from @cychiuae and see what is his use case. And see how to fix the mentioned problem to detect it outside sdk.

> This won't work in iOS because the webview is presented by root view controller and it will always trigger on cancel because app state will be changed from inactive to active when user presses the alert say "Do you want to open xxxx..."

**Comment by cychiuae** [comment]
@carmenlau @louischan-oursky 

First, I think in general having a cancellation signal is very common. Use cases can simple as show/hide loading indicator.

In my business requirement, the flow is Show login dialog -> Slow location permission dialog -> Show push notification permissions dialog. Therefore, I need some completion signal from auth flow (skygear auth ui) to trigger my next flow. 

Also, other common auth sdks have it too. 
google signin sdk: https://github.com/react-native-community/google-signin/blob/7c88a1642addccdb3f2ec5d3bc3c629f5a1c0e9e/index.d.ts#L154
facebook sdk: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b9b55ded4c04ac90dab74bf7b4d3d5f6dcf2de22/types/react-native-fbsdk/index.d.ts#L873
login with apple sdk: https://github.com/invertase/react-native-apple-authentication/blob/719650284b22ba64857d4f2d0277b762cdc2b81a/lib/index.d.ts#L406

**Comment by louischan-oursky** [comment]
Google Sign-in SDK: It is not open source so no idea how they do it. But if it is not using native webview then it is possible to detect viewcontroller/activity destruction.

Facebook SDK: AFAIK, it is using its own viewcontroller/activity so detection is possible.

Login with Apple SDK: Obviously this SDK is targeting new iOS version so cancel detection is bultin.

It is not we do not want to support it. It is due to the design of the SDK so we cannot reliably detect cancellation. Using native webview is considered as a feature rather a design flaw because user does not need to login external Identity (i.e. Google) again.

**Comment by kiootic** [comment]
I see AppAuth is using SFSafariViewController instead: https://github.com/openid/AppAuth-iOS/blob/5d1d8ede8c7ff221973838a8ca2ca50901d7c39e/Source/iOS/OIDExternalUserAgentIOS.m#L152

Maybe we can follow them?

**Comment by louischan-oursky** [comment]
Here is the summary of the current situation.

iOS >= 12.0: ASWebAuthenticationSession; It has cancellation signal.
iOS == 11.0: SFAuthenticationSession; The doc does **not** mention cancellation signal.
iOS == 9.0 or iOS == 10.0: SFSafariViewController; The delegate has dismiss callback.
iOS < 9.0: No need to support such old iOS version

Android CustomTabs: No known API to detect cancellation.
Android WebView: No known API to detect cancellation.

So it is unavoidable that we need a library to detect cancellation.

**Comment by kiootic** [comment]
I see AppAuth seems to have cancellation handled:
https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/library/java/net/openid/appauth/AuthorizationManagementActivity.java#L83

I'm not familiar with Android, but it seems to use a sentinel activity to monitor the completion of web flow?

**Comment by louischan-oursky** [comment]
1. Study how AppAuth does it and borrow their approach
2. Experiment with how AppAuth handles cancel in a real device and study whether [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) propagates cancellation correctly. Study whether react-native-app-auth refreshes token automatically. If the result is positive, we can deprecate the SDK or the SDK simply wrapping these libraries.

**Comment by kiootic** [comment]
A relevant note: it seems [GoogleSignIn](https://github.com/CocoaPods/Specs/blob/master/Specs/d/4/0/GoogleSignIn/5.0.2/GoogleSignIn.podspec.json) is also using AppAuth, so I think it's okay to reuse it in our SDK.

**Comment by louischan-oursky** [comment]
Findings on evaluating AppAuth-iOS, AppAuth-Android and react-native-app-auth

- AppAuth-iOS support cancel from iOS >= 10
- AppAuth-Android support cancel
- react-native-app-auth does not use the API that support cancel from AppAuth-Android.

However, AppAuth-iOS and AppAuth-Android does not expose function to open arbitrary URL, which is needed by our open-settings use-case. Therefore, we should borrow the approach of AppAuth-iOS and AppAuth-Android to handle cancel.
