### ISSUE TITLE
React native upload asset fails in Android

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-SDK-JS#579]
It fails in Android but Ok in iOS

- Android version: 10
- React native version: 0.62
- SDK version: 2.3.0
- file type: image

**Comment by louischan-oursky** [comment]
The FormData API in react native has different behavior depending on Platform.

On Android, we must provide content type. On iOS, content type sometimes can be inferred automatically.

Therefore we have to change the API to take a mandatory content type.
