### ISSUE TITLE
SDK throws error when first time login/signup with facebook using auth ui

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-SDK-JS#584]
It throws `{"error": "invalid_grant", "error_description": "invalid authorization code"}` on the first time but success for the second time. Also, it is showing successfully connected when visit usr identity page.

**Comment by cychiuae** [comment]
related to https://github.com/SkygearIO/skygear-server/issues/1448

**Comment by carmenlau** [comment]
Fixed in https://github.com/SkygearIO/skygear-SDK-JS/pull/585
