### ISSUE TITLE
Support sign up anonymous user

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-JS#61]

**Comment by cheungpat** [comment]
@rickmak not sure if this is match what you have in mind: I will add `signupAnonymously()` taking no arguments which will send a `auth:signup` request with `username`, `email` and `password` being `null`.

This matches the behaviour of the iOS SDK.

**Comment by cheungpat** [comment]
@rickmak said need to allow the modifying username of a user in JS SDK.
