### ISSUE TITLE
Failed to upload assets with spaces&symbol in its names

### ISSUE THREAD

**Issue by klam00** [SkygearIO/skygear-SDK-JS#70]
```
          const attachment = new skygear.Asset({
            name: value.file.name,
            file: value.file
          });
```

Portal Assets Setting:

```
ASSET_STORE_PUBLIC: YES
```

With value.file.name containing a space, I will get 403 (Forbidden) from amazon s3.

```
https://s3-us-west-2.amazonaws.com/skygear-cloud-asset/landingpagegentest/3607751b-219a-4046-97f3-2bdbd0cbe748-sf%20%281%29.jpeg 403 (Forbidden)
```
- Skygear SDK Date/Version:
- JS runtime:
- Skygear Server Date/Version:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

**Comment by ben181231** [comment]
This is identified as a bug in Skygear Cloud Asset. Will be fixed after the fix is deployed.

**Comment by ben181231** [comment]
@klam00 the fix has been deployed. You can check whether it works on your app now.
